### ISSUE TITLE
Extension suddenly stopped accepting NOT gates.

### ISSUE THREAD

**Issue by NatiG7** [jainpranav1/Nand2Tetris-HDL-Visualizer#9]
After using the xtension successfully yesterday, today was slightly different.

![image](https://github.com/jainpranav1/Nand2Tetris-HDL-Visualizer/assets/157003150/75135e9b-5680-452b-b635-4ed1c31453f6)

I encountered this, and narrowed the issue down to the Not gate. it seems that all NOT gates stopped working in all hdl files when visualizing. 

Removing the NOT gate statement solves the error.

**Comment by NatiG7** [comment]
For reference : 
SyntaxError: Expected [a-z,A-Z], comment, or whitespace but ")" found.

Cant indentify the specific character/line/col that the problem appears in.

Edit2*: Not16 works fine.

**Comment by jainpranav1** [comment]
Hey! Thank you for the issue. Let me take a look to see what is the defect.

**Comment by NatiG7** [comment]
at MessagePortMain.emit (node:events:517:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285) nand2tetris-hdl-visualizer.visualize {"value":"PranavJain.nand2tetris-hdl-visualizer","_lower":"pranavjain.nand2tetris-hdl-visualizer"}

at new peg$SyntaxError ---->  node_modules\hdl-parser\src\index.js:14:20)
at peg$buildStructuredError ----- > node_modules\hdl-parser\src\index.js:414:12)
at Object.peg$parse [as parse] ----> node_modules\hdl-parser\src\index.js:1708:11)
also found at 
extensions\pranavjain.nand2tetris-hdl-visualizer-0.0.5\extension.js:103:30

    
On another machine, same error but different char.

**Comment by NitishM2022** [comment]
Has this been fixed. Encountering the same issue

**Comment by jainpranav1** [comment]
sorry, not yet. I'll take some time this december to fix the issue.

**Comment by jainpranav1** [comment]
Sorry for the delay. So I tried running the file @NatiG7 provided on my computer, and it works for me.

```
CHIP FMux {
    IN a,b,sel;
    OUT FMux;

    PARTS:
    Not(in=sel, out=notsel);
    And(a=a,b=notsel,out=notselA);
    And(a=b,b=sel,out=Bsel);
    Or(a=notselA,b=Bsel,out=FMux);
}
```

![image](https://github.com/user-attachments/assets/4167a224-3ee9-4bb6-a49a-8fddd7bd7cb2)

**Comment by jainpranav1** [comment]
The errors mentioned above are syntax errors. These syntax errors are a result of an error when parsing the hdl file. The parser I am using is hdl-parser (https://www.npmjs.com/package/hdl-parser?activeTab=code).

**Comment by jainpranav1** [comment]
This error is difficult to debug for me as I am not able to replicate it. I would suggest the following:
- try reading the thread here as the error is quite similar: https://github.com/jainpranav1/Nand2Tetris-HDL-Visualizer/issues/6

**Comment by jainpranav1** [comment]
Please let me know if the above helps you solve your issues. If not, I would love to help debug more.
